### PR TITLE
remove code duplication

### PR DESCRIPTION
**Pull request by lastw**
In javascript it is not necessary to do things twice

### CODE REVIEW

**Comment by Diokuz** [comment]
> In javascript it is not necessary to do things twice
You sure about this?

**Comment by lastw** [comment]
@Diokuz http://jsfiddle.net/lastw/fuvt0hnv/

**Comment by Diokuz** [comment]
Не работает

**Comment by Diokuz** [comment]
fixed https://github.com/Diokuz/baron/commit/dac736883426af18095efba614c170931297a6dc

**Pull request closed without merging**
